import type { Metadata } from 'next'
/* import { Inter } from 'next/font/google' */
import './globals.css' 
import { DynamicButtonTheme } from '@/components/ButtonTheme'

/* const inter = Inter({ subsets: ['latin'] }) */

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" px-[5%]  min-h-screen  bg-slate-200 dark:bg-slate-900">
        <DynamicButtonTheme />
        {children}</body>
    </html>
  )
}
